### ISSUE TITLE
Make connection Keep-Alive

### ISSUE THREAD

**Issue by Nightflyyer** [Itsyuka/KaiBanchoo-Web#12]
What would Keep-Alive do? Well it would allow for online user panels to be despawned and more!

**Comment by Itsyuka** [comment]
I was just going to update it.

**Comment by Itsyuka** [comment]
I haven't seen a difference so far with my initial tests, but I did add it.

**Comment by Itsyuka** [comment]
https://github.com/Itsyuka/KaiBanchoo-Web/commit/c61173a1d5c55eafbaf6fdae11cb5107cfb59e98
